name: CI Pipeline

on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - feature/create_github_action

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - uses: pre-commit/action@v3.0.0
            # pre-commit run --from-ref origin/HEAD --to-ref HEAD
            # https://pre-commit.com/#usage-in-continuous-integration
